/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_MatrixNative */

#ifndef _Included_main_MatrixNative
#define _Included_main_MatrixNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_MatrixNative
 * Method:    nativeMultiply
 * Signature: ([[D[[D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_main_MatrixNative_nativeMultiply
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
