/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MultiMatriz */

#ifndef _Included_MultiMatriz
#define _Included_MultiMatriz
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MultiMatriz
 * Method:    multiMatrizNativo
 * Signature: ([[I[[I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_MultiMatriz_multiMatrizNativo
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
